// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeui6rCLDk-A7pFPYs7YA2Vsi9Dk3z3zY',
    appId: '1:436339789203:web:b14a67140f39c67cc7ec66',
    messagingSenderId: '436339789203',
    projectId: 'social-media-app-8aebf',
    authDomain: 'social-media-app-8aebf.firebaseapp.com',
    storageBucket: 'social-media-app-8aebf.appspot.com',
    measurementId: 'G-RF3KC70NM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0Pj9BowmApsNcT7gCZrHivnrzJF-UstI',
    appId: '1:436339789203:android:06b83f1ae04e9f77c7ec66',
    messagingSenderId: '436339789203',
    projectId: 'social-media-app-8aebf',
    storageBucket: 'social-media-app-8aebf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz9suDnYecwL_-Ppk9CUVG5UlGVXI95vg',
    appId: '1:436339789203:ios:a93ac3ff0b675833c7ec66',
    messagingSenderId: '436339789203',
    projectId: 'social-media-app-8aebf',
    storageBucket: 'social-media-app-8aebf.appspot.com',
    iosBundleId: 'com.example.minimalSocialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz9suDnYecwL_-Ppk9CUVG5UlGVXI95vg',
    appId: '1:436339789203:ios:93366421606eb7d8c7ec66',
    messagingSenderId: '436339789203',
    projectId: 'social-media-app-8aebf',
    storageBucket: 'social-media-app-8aebf.appspot.com',
    iosBundleId: 'com.example.minimalSocialMediaApp.RunnerTests',
  );
}
